version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: on-failure
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn -c config/gunicorn_config.py ECommerceSite.wsgi"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=django_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

    depends_on:
      - db

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    ports:
      - '6379:6379'
